In [1]:
import numpy as np

In [7]:
A = np.array([[1,4],[3,2]])
print(A)

[[1 4]
 [3 2]]


In [8]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-2.,  5.]), eigenvectors=array([[-0.8       , -0.70710678],
       [ 0.6       , -0.70710678]]))

In [9]:
L,V = np.linalg.eig(A)

In [15]:
L

array([-2.,  5.])

In [11]:
V

array([[-0.8       , -0.70710678],
       [ 0.6       , -0.70710678]])

In [19]:
print(np.round(L,decimals=1))

[-2.  5.]


In [20]:
print(np.round(V,decimals=1))

[[-0.8 -0.7]
 [ 0.6 -0.7]]


In [ ]:
# AV = l*V

In [27]:
#AV
np.dot(A,V[:,0])

array([ 1.6, -1.2])

In [24]:
# l*v
print(L[0])
V[:,0]

-2.0


array([-0.8,  0.6])

In [25]:
L[0] * V[:,0]

array([ 1.6, -1.2])

In [28]:
A = np.array([[1,2,3],[0,3,0],[0,0,1]])
print(A)

[[1 2 3]
 [0 3 0]
 [0 0 1]]


In [31]:
np.linalg.eig(A)

EigResult(eigenvalues=array([1., 3., 1.]), eigenvectors=array([[ 1.00000000e+00,  7.07106781e-01, -1.00000000e+00],
       [ 0.00000000e+00,  7.07106781e-01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  7.40148683e-17]]))

In [35]:
L,V = np.linalg.eig(A)
print(np.round(L,decimals=1))

[1.  0.4 0.7]


In [36]:
print(np.round(V,decimals=1))

[[ 1.   0.8 -0.9]
 [ 0.   0.6  0. ]
 [ 0.   0.   0.4]]


In [37]:
import sympy as sp


In [39]:
A = sp.Matrix([[1,2,3],[0,3,0],[0,0,1]])
A

Matrix([
[1, 2, 3],
[0, 3, 0],
[0, 0, 1]])

In [40]:
A.eigenvals()

{3: 1, 1: 2}

In [41]:
A.eigenvects()

[(1,
  2,
  [Matrix([
   [1],
   [0],
   [0]])]),
 (3,
  1,
  [Matrix([
   [1],
   [1],
   [0]])])]