In [1]:
import numpy as np

In [2]:
a = np.array([[6,4,24],[1,-9,8]])
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(2, 3)

In [5]:
a.size

6

In [6]:
a[0]

array([ 6,  4, 24])

In [7]:
a[1]

array([ 1, -9,  8])

In [8]:
print(a)
a[:,0]

[[ 6  4 24]
 [ 1 -9  8]]


array([6, 1])

In [9]:
a[:,1]

array([ 4, -9])

In [10]:
a[0][0]

6

In [11]:
a[1][2]

8

In [12]:
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [13]:
b = np.array([[6,4,24],[1,-9,8],[1,2,3]])

In [14]:
b[0:2]

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [15]:
b[0:2,1]

array([ 4, -9])

In [16]:
a.sum()

34

In [17]:
a.sum(axis=0)

array([ 7, -5, 32])

In [18]:
a.sum(axis=1)

array([34,  0])

In [19]:
c = a * 2
print(c)

[[ 12   8  48]
 [  2 -18  16]]


In [20]:
a = np.array([[4,5],[2,0]])
b = np.array([[4,6],[1,1]])
print(a)
print(b)

[[4 5]
 [2 0]]
[[4 6]
 [1 1]]


In [21]:
print(a+b)

[[ 8 11]
 [ 3  1]]


In [22]:
print(a-b)

[[ 0 -1]
 [ 1 -1]]


In [23]:
print(a*b)

[[16 30]
 [ 2  0]]


In [24]:
np.dot(a,b)

array([[21, 29],
       [ 8, 12]])

In [25]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,11],[20,21],[30,31]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[10 11]
 [20 21]
 [30 31]]


In [26]:
a.shape

(2, 3)

In [27]:
b.shape

(3, 2)

In [28]:
np.dot(a,b)

array([[140, 146],
       [320, 335]])

In [29]:
np.dot(b,a)

array([[ 54,  75,  96],
       [104, 145, 186],
       [154, 215, 276]])

In [30]:
print(a)

[[1 2 3]
 [4 5 6]]


In [31]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
a.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a = np.array([[0,1,2],[1,7,8],[2,8,9]])
print(a)
print(a == a.T)

[[0 1 2]
 [1 7 8]
 [2 8 9]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [34]:
np.trace(a)

16

In [35]:
np.trace(a.T)

16

In [36]:
x = np.array([[8,3],[4,2]])

In [37]:
print(x)

[[8 3]
 [4 2]]


In [38]:
np.linalg.det(x)

3.999999999999999

In [41]:
y = np.array([[1,2,3],[3,1,2],[0,0,1]])
print(y)

[[1 2 3]
 [3 1 2]
 [0 0 1]]


In [42]:
np.linalg.det(y)

-5.000000000000001

In [43]:
z = np.array([[5,1,6],[0,1,2],[0,0,1]])
print(z)

[[5 1 6]
 [0 1 2]
 [0 0 1]]


In [44]:
np.linalg.det(z)

4.999999999999999

In [46]:
a = np.array([[4,3],[3,2]])
print(a)

[[4 3]
 [3 2]]


In [47]:
np.linalg.inv(a)

array([[-2.,  3.],
       [ 3., -4.]])

In [48]:
b = np.array([[1,2,3],[0,1,4],[5,6,0]])
print(b)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [49]:
np.linalg.inv(b)

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [50]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [51]:
(1**2+2**2+3**2+4**2)** 0.5


5.477225575051661

In [52]:
np.linalg.norm(a)

5.477225575051661

In [53]:
np.sqrt(np.trace(a.dot(a.T)))

5.477225575051661

In [54]:
import sympy as sp

In [56]:
a = sp.Matrix([[-6,3],[4,5]])
a

Matrix([
[-6, 3],
[ 4, 5]])

In [57]:
a.row(0)

Matrix([[-6, 3]])

In [58]:
a.col(0)

Matrix([
[-6],
[ 4]])

In [59]:
a.shape

(2, 2)

In [60]:
a.inv()

Matrix([
[-5/42, 1/14],
[ 2/21,  1/7]])

In [61]:
a.det()

-42

In [64]:
b = sp.Matrix([[8,3],[4,2]])
b


Matrix([
[8, 3],
[4, 2]])

In [65]:
b.det()

4

In [66]:
sp.zeros(4,5)

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [67]:
sp.eye(5)

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

In [68]:
sp.diag(1,2,3,4)

Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0],
[0, 0, 0, 4]])