In [9]:
import numpy as np

In [10]:
a = np.array([[6,4,24],[1,-9,8]])
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [11]:
type(a)

numpy.ndarray

In [12]:
a.shape

(2, 3)

In [13]:
a.size

6

In [16]:
a[0]

array([ 6,  4, 24])

In [15]:
a[1]

array([ 1, -9,  8])

In [18]:
print(a)
a[:,0]

[[ 6  4 24]
 [ 1 -9  8]]


array([6, 1])

In [19]:
a[:,1]

array([ 4, -9])

In [20]:
a[0][0]

6

In [21]:
a[1][2]

8