In [1]:
import numpy as np

In [2]:
a = np.array([[6,4,24],[1,-9,8]])
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(2, 3)

In [5]:
a.size

6

In [6]:
a[0]

array([ 6,  4, 24])

In [7]:
a[1]

array([ 1, -9,  8])

In [8]:
print(a)
a[:,0]

[[ 6  4 24]
 [ 1 -9  8]]


array([6, 1])

In [9]:
a[:,1]

array([ 4, -9])

In [10]:
a[0][0]

6

In [11]:
a[1][2]

8

In [12]:
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [19]:
b = np.array([[6,4,24],[1,-9,8],[1,2,3]])

In [20]:
b[0:2]

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [21]:
b[0:2,1]

array([ 4, -9])

In [22]:
a.sum()

34

In [23]:
a.sum(axis=0)

array([ 7, -5, 32])

In [24]:
a.sum(axis=1)

array([34,  0])

In [25]:
c = a * 2
print(c)

[[ 12   8  48]
 [  2 -18  16]]


In [27]:
a = np.array([[4,5],[2,0]])
b = np.array([[4,6],[1,1]])
print(a)
print(b)

[[4 5]
 [2 0]]
[[4 6]
 [1 1]]


In [28]:
print(a+b)

[[ 8 11]
 [ 3  1]]


In [29]:
print(a-b)

[[ 0 -1]
 [ 1 -1]]


In [30]:
print(a*b)

[[16 30]
 [ 2  0]]


In [31]:
np.dot(a,b)

array([[21, 29],
       [ 8, 12]])

In [32]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,11],[20,21],[30,31]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[10 11]
 [20 21]
 [30 31]]


In [35]:
a.shape

(2, 3)

In [36]:
b.shape

(3, 2)

In [37]:
np.dot(a,b)

array([[140, 146],
       [320, 335]])

In [38]:
np.dot(b,a)

array([[ 54,  75,  96],
       [104, 145, 186],
       [154, 215, 276]])

In [39]:
print(a)

[[1 2 3]
 [4 5 6]]


In [40]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
a.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
a = np.array([[0,1,2],[1,7,8],[2,8,9]])
print(a)
print(a == a.T)

[[0 1 2]
 [1 7 8]
 [2 8 9]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [46]:
np.trace(a)

16

In [ ]:
np.trace(a.T)