In [21]:
import numpy as np

In [22]:
A = np.array([[3,1,1],[-1,3,1]])

In [23]:
A.T

array([[ 3, -1],
       [ 1,  3],
       [ 1,  1]])

In [24]:
np.dot(A,A.T)

array([[11,  1],
       [ 1, 11]])

In [25]:
np.dot(A.T,A)

array([[10,  0,  2],
       [ 0, 10,  4],
       [ 2,  4,  2]])

In [26]:
U,S,Vt = np.linalg.svd(A)

In [27]:
print(np.round(U,decimals=1))

[[-0.7 -0.7]
 [-0.7  0.7]]


In [28]:
print(np.round(Vt,decimals=1))

[[-0.4 -0.8 -0.4]
 [-0.9  0.4  0. ]
 [-0.2 -0.4  0.9]]


In [29]:
print(np.round(S,decimals=1))

[3.5 3.2]


In [30]:
# A = U s Vt

In [37]:
s = np.array([[3.5,0,0],[0,3.2,0]])

In [38]:
s.shape

(2, 3)

In [40]:
np.dot(np.dot(U,s),Vt)
print(np.round(np.dot(np.dot(U,s),Vt),decimals=1))

[[ 3.  1.  1.]
 [-1.  3.  1.]]


In [41]:
A

array([[ 3,  1,  1],
       [-1,  3,  1]])