In [1]:
import numpy as np

In [5]:
a = np.array([5,4])
print(a)

[5 4]


In [6]:
type(a)

numpy.ndarray

In [8]:
len(a)

2

In [9]:
a[0]

5

In [10]:
a[1]

4

In [11]:
b = np.array([8,3])
print(b)

[8 3]


In [12]:
print(a,b)


[5 4] [8 3]


In [13]:
a+b

array([13,  7])

In [14]:
np.add(a,b)

array([13,  7])

In [15]:
a - b

array([-3,  1])

In [16]:
a * b

array([40, 12])

In [17]:
np.multiply(a,b)

array([40, 12])

In [19]:
print(a)

[5 4]


In [20]:
np.dot(2,a)

array([10,  8])

In [21]:
print(a,b)

[5 4] [8 3]


In [22]:
np.dot(a,b)

52